### ISSUE TITLE
when i run the train_clf.py，it Appear：KeyError: "Unable to open object (object 'data' doesn't exist)"

### ISSUE THREAD

**Issue by hujunsheng** [yanx27/Pointnet_Pointnet2_pytorch#27]
when i run the train_clf.py
KeyError: "Unable to open object (object 'data' doesn't exist)"
how to solve this problem？
thank you

**Comment by neverstoplearn** [comment]
i meet the same error as you  have you solve it? thanks.

**Comment by malcolmyanguci** [comment]
![Screenshot from 2019-10-25 19-44-16](https://user-images.githubusercontent.com/46518089/67613221-ddffe680-f75f-11e9-8afd-8a5203a5d0d4.png)

I tried to open the "ply_data_train0.h5" in ModelNet. There is no even keys and the file is basically empty. I think this is problem but i dont know how to fix it.

However, the segmentation script can work. :)

**Comment by malcolmyanguci** [comment]
![image](https://user-images.githubusercontent.com/46518089/67613262-58306b00-f760-11e9-9af9-428b41c3ec10.png)

**Comment by xiaodp** [comment]
> when i run the train_clf.py
> KeyError: "Unable to open object (object 'data' doesn't exist)"
> how to solve this problem？
> thank you
The data in the ModelNet40 is end with .off,and the .h5 file is the point cloud data generated from the .off file. And I encountered the same problem at the begening. I solved it by downloading the .h5 files with this link:"https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip" and added them to the dataset .I think the link to the modelNet40 in the "README.md" is not very right,because there isn't any .h5 file when I downloaded it. You can either generate the point cloud files(.h5 files) by yourself or download them form https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip
Best wishes!
