### ISSUE TITLE
about reproducible result on s3dis (semantic segmentation) dataset

### ISSUE THREAD

**Issue by amiltonwong** [yanx27/Pointnet_Pointnet2_pytorch#39]
Hi, @yanx27 ,

I had followed the [steps](https://github.com/yanx27/Pointnet_Pointnet2_pytorch#run-2) on training s3dis (semantic segmentation) dataset and performed testing. However, the test result only gives `0.329263` mIOU (use pointnet2_sem_seg model), which is quite lower than the reported [`0.532` mIOU](https://github.com/yanx27/Pointnet_Pointnet2_pytorch#performance-2). And I found that the trained model performs good segmentation on class ceiling, floor, wall, while it performs almost zero accuracy on class bean, column, window. Is there something wrong in the dataset [preparation](https://github.com/yanx27/Pointnet_Pointnet2_pytorch#data-preparation-2)?
Here are the logs on my training and testing: [pointnet2_sem_seg.txt](https://gist.github.com/amiltonwong/93759bb923fcd729ac4a1f2dcedb2aba), [eval.txt](https://gist.github.com/amiltonwong/e6e29a4cc2b6b3e8d1b591727656805e)

THX!

**Comment by yanx27** [comment]
> Hi, @yanx27 ,
> 
> I had followed the [steps](https://github.com/yanx27/Pointnet_Pointnet2_pytorch#run-2) on training s3dis (semantic segmentation) dataset and performed testing. However, the test result only gives `0.329263` mIOU (use pointnet2_sem_seg model), which is quite lower than the reported [`0.532` mIOU](https://github.com/yanx27/Pointnet_Pointnet2_pytorch#performance-2). And I found that the trained model performs good segmentation on class ceiling, floor, wall, while it performs almost zero accuracy on class bean, column, window. Is there something wrong in the dataset [preparation](https://github.com/yanx27/Pointnet_Pointnet2_pytorch#data-preparation-2)?
> Here are the logs on my training and testing: [pointnet2_sem_seg.txt](https://gist.github.com/amiltonwong/93759bb923fcd729ac4a1f2dcedb2aba), [eval.txt](https://gist.github.com/amiltonwong/e6e29a4cc2b6b3e8d1b591727656805e)
> 
> THX!

Hi, I actually achieved this results by last version code. In this version, I change data loader to randomly chopping points instead of cutting cubes before training, which perform better in tensorflow code. I think there was a problem in padding parameter of data loader and  it was already fixed. You can train it again, and if it still has some problems, I will rewrite them :) btw, I am somehow busy recently.

**Comment by yanx27** [comment]
Hi, @amiltonwong , I have already test new codes, which exactly cannot achieve original results (53 IoU on S3DIS). Because official PointNet use sub-points as training and testing data, which just choose 4096 points on each 1x1 cube and evaluate just on these sub-points. Now our codes test on all of original points, which make more mistakes.  

For old sub-points data, you can download on [here](https://shapenet.cs.stanford.edu/media/indoor3d_sem_seg_hdf5_data.zip) and code for training you can search in history commits, which is relatively simple. Now PointNet2_ssg can achieve 45 mIoU on S3DIS area 5, and you can also try pointnet2_msg by yourself :)

**Comment by czha5168** [comment]
Hi Benny, 
Thanks for your excellent repo! I was testing it on S3DIS and I wonder whether I may have your confirmation on your current processing of S3DIS dataset, please?
According to the official pointnet repo, it seems the S3DIS has been preprocessed through two steps, including (1) adopting "collect_indoor3d_data.py" to convert raw data to npy files and followed by (2) "gen_indoor3d_h5.py" to convert npy files to h5 files. 
In your latest repo, have you completed step 1, so that the training can be completed with the PointNet-Official-Preprocessed-4096-PointCloud data? Also, is there any performance improvement to be expected if training them on h5 files instead (or merely a training speed increment)? 
Thanks for your time and help!

**Comment by lianghouhao** [comment]
Hello, @czha5168  I don't think author did this step as official pointnet repo, which used pre-processed s3dis on hdf5 data. In this repo, author directly manipulate npy/txt data as input. So you don't need official preprocessed hdf5 dataset. 

Hi, @yanx27 
I can't achieve published result on Pointnet s3dis, around 10% less mean class iou. I was wondering the reason should be the way you select the pts in each block. Seems you randomly selected a center point and did the sampling task. A little different as original repo. 
Thanks for your confirmation.

**Comment by czha5168** [comment]
@lianghouhao Hi Houhao, Thanks for your reply. It seems in pointnet official repo, each training sample (consisting of 4096 points) is randomly selected on room-blocks, which means, in other words, the semseg model is trained on the self-preprocessed block-level, rather than the room-level. Could you please help me with this clarification if possible? Cheers.

**Comment by lianghouhao** [comment]
> @lianghouhao Hi Houhao, Thanks for your reply. It seems in pointnet official repo, each training sample (consisting of 4096 points) is randomly selected on room-blocks, which means, in other words, the semseg model is trained on the self-preprocessed block-level, rather than the room-level. Could you please help me with this clarification if possible? Cheers.

Well. In my view, it is block-level. For each room space, they selected several 4096 points blocks as training samples. And these blocks make up the room. But It's not randomly selected.
