### ISSUE TITLE
Question about the mean class accuracy about ModelNet40

### ISSUE THREAD

**Issue by grxiao** [yanx27/Pointnet_Pointnet2_pytorch#41]
The mean class accuracy is not seen in the paper, may I ask why this is?
It is difficult to obtain the accuracy of 90.7 in the repetition experiment, so I want to consult the mean class accuracy.

Thanks!

**Comment by yanx27** [comment]
Hi, @grxiao mean class accuracy and overall accuracy are not the same, and will get relatively low results in former one, because the Modelnet data actually has unbalanced categories, most of the instance are airplanes or chairs, etc. You can get very high accuracy rate on them, however, some small categories have low accuracy.

btw. Some recent paper records this comparison such as [ACNN](http://openaccess.thecvf.com/content_CVPR_2019/papers/Komarichev_A-CNN_Annularly_Convolutional_Neural_Networks_on_Point_Clouds_CVPR_2019_paper.pdf)

**Comment by grxiao** [comment]
Thanks for your help！@yanx27
