### ISSUE TITLE
RuntimeError: Given groups=1, weight of size 64 6 1, expected input[16, 9, 4096] to have 6 channels, but got 9 channels instead

### ISSUE THREAD

**Issue by ZJU-PLP** [yanx27/Pointnet_Pointnet2_pytorch#45]
Hi, when I run the **python train_semseg.py --gpu 1 --log_dir pointnet_sem_seg**. I find the following error:
**RuntimeError: Given groups=1, weight of size 64 6 1, expected input[16, 9, 4096] to have 6 channels, but got 9 channels instead**
Could you mind telling the solution? Thanks a lot!

**Comment by yanx27** [comment]
@ZJU-PLP Hi, already fixed~

**Comment by ZJU-PLP** [comment]
> @ZJU-PLP Hi, already fixed~

ok.tks a lot!

**Comment by ZJU-PLP** [comment]
@yanx27 tks a lot!

**Comment by PemasiriAkila** [comment]
Hi @ZJU-PLP  and @yanx27 , I still keep getting the same error. Can you please let me know how you have solved it? Thanks a lot

**Comment by Jangliu** [comment]
me too. the same problem

**Comment by PointCloudYC** [comment]
The error is mainly due to the data examples from S3DIS dataset have 9 channels that involve xyzrgb and normalized XYZ. However, the code is hardcoded supporting only 3 or 6 channels. To fix this issue, some minor modifications should be made.
3 places should be modified.
- pointnet_sem_seg.py; 
```
class get_model(nn.Module):
    def __init__(self, num_class, with_rgb=True, with_normalized_xyz=True):
        super(get_model, self).__init__()
        if with_rgb:
            channel = 6
            if with_normalized_xyz:
                channel= 9
        else:
            ...
```

- pointnet.py; change PointNetEncoder's forward method 
```
        if D >3 :
            x, feature = x.split([3,D-3],dim=2)
```

Note: the code assumes each data example has 9 channels. For classification, the modification should be made accordingly.
