### ISSUE TITLE
Does it slow since it do not implement the FPS and Query_ball in cuda?

### ISSUE THREAD

**Issue by zeal-github** [yanx27/Pointnet_Pointnet2_pytorch#50]
Have you tested the speed gap between your implementation(I notice that all the implement is pure python) and the cuda implementation of other source code?
I just curious about it. How you can give me a reply. Thanks!

**Comment by yanx27** [comment]
Hi, @zeal-github~ When test in classification and part segmentation tasks, the time used is basically the same, even faster, because torch is multi-threaded when feeding data. However, if the number of points gradually increases, such as 4096 or 8192, the speed will be much slower than the version of cuda, and the GPU usage will be higher.

**Comment by zeal-github** [comment]
@yanx27 Thanks！I have tried to find pure python implementation for a long time! It's useful for me.

**Comment by WhatAShot** [comment]
Hi, @yanx27 . I think the main cause of the lower speed with increased point number is the FPS but not query_ball. Is it right?

**Comment by tangbohu** [comment]
Could report the time for training the classification module. It is a bit slow in my computer.

**Comment by yanx27** [comment]
@tangbohu Maybe 8-10 min for pointnet2_cls_msg and 1 min for pointnet. You can adaptively change num_works [here](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/2d08fa40635cc5eafd14d19d18e3dc646171910d/train_cls.py#L106) (e.g., 20)
