### ISSUE TITLE
Failed to download 3D indoor parsing dataset (S3DIS)

### ISSUE THREAD

**Issue by Xelawk** [yanx27/Pointnet_Pointnet2_pytorch#79]
It was something wrong happened when downloading 3D indoor parsing dataset (S3DIS) by visiting [S3DIS](http://buildingparser.stanford.edu/dataset.html). The error message is pasted below:
# Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /dataset.html.

Reason: **Error reading from remote server**

**Comment by kukuruza** [comment]
Run this in the terminal:

`wget https://shapenet.cs.stanford.edu/media/shapenetcore_partanno_segmentation_benchmark_v0_normal.zip --no-check-certificate`

**Comment by NickSadjoli** [comment]
Hi, I'm chipping in since I had a similar issue of downloading the raw (.txt data format, not the processed .h5 data format that is used for the Testing done on the Semantic Segmentatino) S3DIS dataset myself. As mentioned by you and many others  - including people from other project, including the [PointNet Github page](https://github.com/charlesq34/pointnet/issues/105) - relying on the raw S3DIS dataset, the original link provided (http://buildingparser.stanford.edu/dataset.html) seems to have gone down as of recently (seems to have occurred within the period of last month).

After some searching, I found that the Torch 3D Library Project seem has access to such raw data, having its url embedded as part of their code as shown in one of their documentation pages for their integration of the [S3DIS dataset](https://torch-points3d.readthedocs.io/en/latest/_modules/torch_points3d/datasets/segmentation/s3dis.html). Officially, you'll need to access the dataset through a link that will be provided by this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLScDimvNMCGhy_rmBA2gHfDu3naktRm6A8BPwAWWDv-Uhm6Shw/viewform?c=0&w=1&fbzx=2673084470089026507) page. You should be greeted with a Google Doc page containing the raw data and download them from there.

I myself am not sure why such link has been taken down by Stanford, but I believe all projects relying on the original raw S3DIS dataset should have their reference links updated. In this case, I'm hoping that @yanx27 could help update the README of this project to accommodate the semantic segmentation training of your PointNet implementation as well.

**Comment by Ashkan-1993** [comment]
https://shapenet.cs.stanford.edu/media/indoor3d_sem_seg_hdf5_data.zip
here you can do it

**Comment by Wuziyi616** [comment]
@NickSadjoli Wow! Thank you so much for your comment! Are you sure the link you provided is exactly the same S3DIS dataset as the old link? I'm new in this area so I just want to make sure it again. Thanks!

**Comment by Brodong** [comment]
> https://shapenet.cs.stanford.edu/media/indoor3d_sem_seg_hdf5_data.zip
> here you can do it

This link is not available also.

**Comment by Atta66** [comment]
> https://shapenet.cs.stanford.edu/media/indoor3d_sem_seg_hdf5_data.zip here you can do it

I cannot access the site but this works! Thanks

**Comment by koi-boy** [comment]
tks

**Comment by bnddwwj** [comment]
txt格式：
https://docs.google.com/forms/d/e/1FAIpQLScDimvNMCGhy_rmBA2gHfDu3naktRm6A8BPwAWWDv-Uhm6Shw/viewform?c=0&w=1

**Comment by dipeshgyawali** [comment]
> https://shapenet.cs.stanford.edu/media/indoor3d_sem_seg_hdf5_data.zip here you can do it

Thank you for the link. I see there are 9 features value associated value. I believe the first 3 are x,y,z coordinates as there are some negative values associated with it. Can you tell what are the other features/values inside the data? Is the data in this(xyz, rgb, intensity, normal, curvature) format?
